### ISSUE TITLE
TS: TypeError (reading 'enableSubmit') when disabling the submitButton

### ISSUE THREAD

**Issue by hannes111** [sparna-git/Sparnatural#629]
When setting the option "submitButton" to false, a "_TypeError: Cannot read properties of undefined (reading 'enableSubmit'_)" is thrown. 

sparnatural@9.5.1
next@14.2.8
typescript@5.5.4

Configuration:
<spar-natural
    ref={sparnaturalRef}
    src={`/api/file-proxy?action=download&filename=${filename || 'ocqasparnatural.ttl'}`}
    endpoint="/api/sparql-proxy"
    lang="en"
    defaultLang="en"
    distinct="true"
    limit="0"
    prefix="ocqa:https://w3id.org/ocqa# ocqa-con:https://w3id.org/ocqa-contract#"
    debug="false"

**submitButton="false"**

   useragent='sparnatural'
/>

Error: 
sparnatural.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'enableSubmit')
    at ko.generateQuery (sparnatural.js:3:1805618)
    at HTMLDivElement.eval (sparnatural.js:3:1806686)
    at X.K (sparnatural.js:3:1599131)
    at H.eval [as callBack] (sparnatural.js:3:1600991)
    at SVGSVGElement.eval (sparnatural.js:3:1596740)
    at SVGSVGElement.dispatch (sparnatural.js:3:562976)
    at m.handle (sparnatural.js:3:560971)
    at Tr.autoSelectEyeBtn (sparnatural.js:3:1686439)
    at HTMLDivElement.eval (sparnatural.js:3:1684940)
    at HTMLSelectElement.eval (sparnatural.js:3:1598966)
    at HTMLSelectElement.dispatch (sparnatural.js:3:562976)
    at m.handle (sparnatural.js:3:560971)
    at Object.trigger (sparnatural.js:3:591664)
    at HTMLSelectElement.eval (sparnatural.js:3:592260)
    at Function.each (sparnatural.js:3:522915)
    at S.fn.init.each (sparnatural.js:3:521395)
    at S.fn.init.trigger (sparnatural.js:3:592235)
    at HTMLDivElement.eval (sparnatural.js:3:307218)
    at HTMLDocument.dispatch (sparnatural.js:3:562976)
    at m.handle (sparnatural.js:3:560971)

**Comment by tfrancart** [comment]
This should be fixed by the latest commit. Let me know if you can recompile and test on your side

**Comment by hannes111** [comment]
I am using the npm, where the current version is 9.5.1.

**Comment by tfrancart** [comment]
@hannes111 apologies as the npm was not up-to-date compared to Github releases. This is fixed now and the latest 9.5.2 on npm should fix this bug

**Comment by hannes111** [comment]
Wonderful working great! thanks!
