### ISSUE TITLE
When variable is aggregated, and a line in the query is deleted, then the aggregated query gets wrongly deleted from the variable panel

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural#646]
If I load a preset query with a count and then modify this query, I will get an error in the console and the UI for the aggregation empties:

```
SparqlGenerator.ts:55 Uncaught TypeError: Cannot read properties of undefined (reading 'selectedVariable')
    at po.generateQuery (SparqlGenerator.ts:55:39)
    at fo.generateQuery (GenerateQuery.ts:51:32)
    at HTMLDivElement.<anonymous> (ActionStore.ts:52:34)
    at RemoveEndClass.ts:45:22
    at HTMLLIElement.<anonymous> (GroupWrapperEventStore.ts:36:9)
    at ClassTypeId.ts:118:20
    at HTMLSpanElement.<anonymous> (UnselectBtn.ts:10:7)
    at HTMLSpanElement.dispatch (jquery.js:5430:27)
    at e.9755.S.event.add.m.handle (jquery.js:5234:28)
```

example query:
```json
{
  "distinct": true,
  "variables": [
    {
      "expression": {
        "type": "aggregate",
        "aggregation": "count",
        "distinct": false,
        "expression": {
          "termType": "Variable",
          "value": "institution_1"
        }
      },
      "variable": {
        "termType": "Variable",
        "value": "institution_1_count"
      }
    },
    {
      "termType": "Variable",
      "value": "region_4"
    }
  ],
  "order": null,
  "branches": [
    {
      "line": {
        "s": "institution_1",
        "p": "http://www.graceful17.org/shacl/sparnatural-config/primary_place",
        "o": "place_2",
        "sType": "http://www.graceful17.org/shacl/sparnatural-config/institution",
        "oType": "http://www.graceful17.org/shacl/sparnatural-config/place",
        "values": []
      },
      "children": [
        {
          "line": {
            "s": "place_2",
            "p": "http://www.graceful17.org/shacl/sparnatural-config/falls_within",
            "o": "region_4",
            "sType": "http://www.graceful17.org/shacl/sparnatural-config/place",
            "oType": "http://www.graceful17.org/shacl/sparnatural-config/region",
            "values": []
          },
          "children": []
        }
      ]
    }
  ]
}
```
![grafik](https://github.com/user-attachments/assets/ad57a483-9d62-4664-975a-57d528c049c2)

**Comment by tfrancart** [comment]
I cannot reproduce. Could you be more precise on the sequence of action you are taking to reproduce the bug ? what **exactly** are you modifying after loading the query ?

**Comment by ch-sander** [comment]
Sure!

https://github.com/user-attachments/assets/55695b72-77a0-4d93-a1b2-c18520861219

1. I open (or create) a query that has more than one branch. I used one that has a count aggregation, but maybe that's not even the issue.
2. I delete on line/branch in the query
3. the panel for aggregation/sort will then be empty. The query still works, though.

**Comment by tfrancart** [comment]
Reproduced with either:

First query aggregated : "Artwork -> Museum + Museum -> Country, then count(Artwork), then delete line Museum -> Country"
Second query aggregated : same query, but aggregate on Museum and don't select Artwork

**Comment by ch-sander** [comment]
I'll retry with your demo instance and report back

**Comment by tfrancart** [comment]
Fixed. Thanks @ch-sander for the details provided, the screencast helped a lot. The problem was indeed with aggregated variables
